M48
; DRILL file {KiCad 9.0.7} date 2026-03-05T05:57:34-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-05T05:57:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X6.985Y33.02
X15.875Y33.02
X24.765Y33.02
T2
X6.985Y37.52
X15.875Y37.52
X24.765Y37.52
M30
